
type _arr_flat_test = {
"ArrayType.Flat<[1]>?":ArrayType.Flat<[]>;
"ArrayType.Flat<[2]>?":ArrayType.Flat<[][]>;
"ArrayType.Flat<[3]>?":ArrayType.Flat<[][][]>;
"ArrayType.Flat<[4]>?":ArrayType.Flat<[][][][]>;
"ArrayType.Flat<[5]>?":ArrayType.Flat<[][][][][]>;
"ArrayType.Flat<[6]>?":ArrayType.Flat<[][][][][][]>;
"ArrayType.Flat<[7]>?":ArrayType.Flat<[][][][][][][]>;
"ArrayType.Flat<[8]>?":ArrayType.Flat<[][][][][][][][]>;
"ArrayType.Flat<[9]>?":ArrayType.Flat<[][][][][][][][][]>;
"ArrayType.Flat<[10]>?":ArrayType.Flat<[][][][][][][][][][]>;
"ArrayType.Flat<[11]>?":ArrayType.Flat<[][][][][][][][][][][]>;
"ArrayType.Flat<[12]>?":ArrayType.Flat<[][][][][][][][][][][][]>;
"ArrayType.Flat<[13]>?":ArrayType.Flat<[][][][][][][][][][][][][]>;
"ArrayType.Flat<[14]>?":ArrayType.Flat<[][][][][][][][][][][][][][]>;
"ArrayType.Flat<[15]>?":ArrayType.Flat<[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[16]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[17]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[18]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[19]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[20]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[21]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[22]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[23]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[24]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[25]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[26]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[27]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[28]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[29]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[30]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[31]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[32]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[33]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[34]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[35]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[36]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[37]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[38]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[39]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[40]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[41]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[42]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[43]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[44]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[45]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[46]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[47]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[48]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[49]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<[50]>?":ArrayType.Flat<[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type unknown_arr_flat_test = {
"ArrayType.Flat<unknown[1]>?":ArrayType.Flat<unknown[]>;
"ArrayType.Flat<unknown[2]>?":ArrayType.Flat<unknown[][]>;
"ArrayType.Flat<unknown[3]>?":ArrayType.Flat<unknown[][][]>;
"ArrayType.Flat<unknown[4]>?":ArrayType.Flat<unknown[][][][]>;
"ArrayType.Flat<unknown[5]>?":ArrayType.Flat<unknown[][][][][]>;
"ArrayType.Flat<unknown[6]>?":ArrayType.Flat<unknown[][][][][][]>;
"ArrayType.Flat<unknown[7]>?":ArrayType.Flat<unknown[][][][][][][]>;
"ArrayType.Flat<unknown[8]>?":ArrayType.Flat<unknown[][][][][][][][]>;
"ArrayType.Flat<unknown[9]>?":ArrayType.Flat<unknown[][][][][][][][][]>;
"ArrayType.Flat<unknown[10]>?":ArrayType.Flat<unknown[][][][][][][][][][]>;
"ArrayType.Flat<unknown[11]>?":ArrayType.Flat<unknown[][][][][][][][][][][]>;
"ArrayType.Flat<unknown[12]>?":ArrayType.Flat<unknown[][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[13]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[14]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[15]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[16]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[17]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[18]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[19]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[20]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[21]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[22]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[23]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[24]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[25]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[26]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[27]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[28]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[29]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[30]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[31]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[32]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[33]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[34]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[35]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[36]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[37]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[38]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[39]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[40]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[41]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[42]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[43]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[44]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[45]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[46]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[47]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[48]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[49]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<unknown[50]>?":ArrayType.Flat<unknown[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type any_arr_flat_test = {
"ArrayType.Flat<any[1]>?":ArrayType.Flat<any[]>;
"ArrayType.Flat<any[2]>?":ArrayType.Flat<any[][]>;
"ArrayType.Flat<any[3]>?":ArrayType.Flat<any[][][]>;
"ArrayType.Flat<any[4]>?":ArrayType.Flat<any[][][][]>;
"ArrayType.Flat<any[5]>?":ArrayType.Flat<any[][][][][]>;
"ArrayType.Flat<any[6]>?":ArrayType.Flat<any[][][][][][]>;
"ArrayType.Flat<any[7]>?":ArrayType.Flat<any[][][][][][][]>;
"ArrayType.Flat<any[8]>?":ArrayType.Flat<any[][][][][][][][]>;
"ArrayType.Flat<any[9]>?":ArrayType.Flat<any[][][][][][][][][]>;
"ArrayType.Flat<any[10]>?":ArrayType.Flat<any[][][][][][][][][][]>;
"ArrayType.Flat<any[11]>?":ArrayType.Flat<any[][][][][][][][][][][]>;
"ArrayType.Flat<any[12]>?":ArrayType.Flat<any[][][][][][][][][][][][]>;
"ArrayType.Flat<any[13]>?":ArrayType.Flat<any[][][][][][][][][][][][][]>;
"ArrayType.Flat<any[14]>?":ArrayType.Flat<any[][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[15]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[16]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[17]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[18]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[19]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[20]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[21]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[22]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[23]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[24]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[25]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[26]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[27]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[28]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[29]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[30]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[31]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[32]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[33]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[34]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[35]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[36]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[37]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[38]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[39]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[40]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[41]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[42]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[43]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[44]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[45]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[46]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[47]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[48]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[49]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<any[50]>?":ArrayType.Flat<any[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type never_arr_flat_test = {
"ArrayType.Flat<never[1]>?":ArrayType.Flat<never[]>;
"ArrayType.Flat<never[2]>?":ArrayType.Flat<never[][]>;
"ArrayType.Flat<never[3]>?":ArrayType.Flat<never[][][]>;
"ArrayType.Flat<never[4]>?":ArrayType.Flat<never[][][][]>;
"ArrayType.Flat<never[5]>?":ArrayType.Flat<never[][][][][]>;
"ArrayType.Flat<never[6]>?":ArrayType.Flat<never[][][][][][]>;
"ArrayType.Flat<never[7]>?":ArrayType.Flat<never[][][][][][][]>;
"ArrayType.Flat<never[8]>?":ArrayType.Flat<never[][][][][][][][]>;
"ArrayType.Flat<never[9]>?":ArrayType.Flat<never[][][][][][][][][]>;
"ArrayType.Flat<never[10]>?":ArrayType.Flat<never[][][][][][][][][][]>;
"ArrayType.Flat<never[11]>?":ArrayType.Flat<never[][][][][][][][][][][]>;
"ArrayType.Flat<never[12]>?":ArrayType.Flat<never[][][][][][][][][][][][]>;
"ArrayType.Flat<never[13]>?":ArrayType.Flat<never[][][][][][][][][][][][][]>;
"ArrayType.Flat<never[14]>?":ArrayType.Flat<never[][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[15]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[16]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[17]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[18]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[19]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[20]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[21]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[22]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[23]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[24]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[25]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[26]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[27]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[28]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[29]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[30]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[31]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[32]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[33]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[34]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[35]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[36]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[37]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[38]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[39]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[40]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[41]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[42]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[43]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[44]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[45]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[46]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[47]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[48]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[49]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<never[50]>?":ArrayType.Flat<never[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type void_arr_flat_test = {
"ArrayType.Flat<void[1]>?":ArrayType.Flat<void[]>;
"ArrayType.Flat<void[2]>?":ArrayType.Flat<void[][]>;
"ArrayType.Flat<void[3]>?":ArrayType.Flat<void[][][]>;
"ArrayType.Flat<void[4]>?":ArrayType.Flat<void[][][][]>;
"ArrayType.Flat<void[5]>?":ArrayType.Flat<void[][][][][]>;
"ArrayType.Flat<void[6]>?":ArrayType.Flat<void[][][][][][]>;
"ArrayType.Flat<void[7]>?":ArrayType.Flat<void[][][][][][][]>;
"ArrayType.Flat<void[8]>?":ArrayType.Flat<void[][][][][][][][]>;
"ArrayType.Flat<void[9]>?":ArrayType.Flat<void[][][][][][][][][]>;
"ArrayType.Flat<void[10]>?":ArrayType.Flat<void[][][][][][][][][][]>;
"ArrayType.Flat<void[11]>?":ArrayType.Flat<void[][][][][][][][][][][]>;
"ArrayType.Flat<void[12]>?":ArrayType.Flat<void[][][][][][][][][][][][]>;
"ArrayType.Flat<void[13]>?":ArrayType.Flat<void[][][][][][][][][][][][][]>;
"ArrayType.Flat<void[14]>?":ArrayType.Flat<void[][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[15]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[16]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[17]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[18]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[19]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[20]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[21]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[22]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[23]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[24]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[25]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[26]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[27]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[28]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[29]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[30]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[31]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[32]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[33]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[34]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[35]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[36]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[37]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[38]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[39]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[40]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[41]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[42]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[43]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[44]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[45]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[46]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[47]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[48]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[49]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<void[50]>?":ArrayType.Flat<void[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type undefined_arr_flat_test = {
"ArrayType.Flat<undefined[1]>?":ArrayType.Flat<undefined[]>;
"ArrayType.Flat<undefined[2]>?":ArrayType.Flat<undefined[][]>;
"ArrayType.Flat<undefined[3]>?":ArrayType.Flat<undefined[][][]>;
"ArrayType.Flat<undefined[4]>?":ArrayType.Flat<undefined[][][][]>;
"ArrayType.Flat<undefined[5]>?":ArrayType.Flat<undefined[][][][][]>;
"ArrayType.Flat<undefined[6]>?":ArrayType.Flat<undefined[][][][][][]>;
"ArrayType.Flat<undefined[7]>?":ArrayType.Flat<undefined[][][][][][][]>;
"ArrayType.Flat<undefined[8]>?":ArrayType.Flat<undefined[][][][][][][][]>;
"ArrayType.Flat<undefined[9]>?":ArrayType.Flat<undefined[][][][][][][][][]>;
"ArrayType.Flat<undefined[10]>?":ArrayType.Flat<undefined[][][][][][][][][][]>;
"ArrayType.Flat<undefined[11]>?":ArrayType.Flat<undefined[][][][][][][][][][][]>;
"ArrayType.Flat<undefined[12]>?":ArrayType.Flat<undefined[][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[13]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[14]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[15]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[16]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[17]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[18]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[19]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[20]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[21]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[22]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[23]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[24]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[25]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[26]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[27]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[28]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[29]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[30]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[31]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[32]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[33]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[34]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[35]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[36]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[37]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[38]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[39]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[40]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[41]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[42]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[43]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[44]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[45]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[46]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[47]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[48]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[49]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<undefined[50]>?":ArrayType.Flat<undefined[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type null_arr_flat_test = {
"ArrayType.Flat<null[1]>?":ArrayType.Flat<null[]>;
"ArrayType.Flat<null[2]>?":ArrayType.Flat<null[][]>;
"ArrayType.Flat<null[3]>?":ArrayType.Flat<null[][][]>;
"ArrayType.Flat<null[4]>?":ArrayType.Flat<null[][][][]>;
"ArrayType.Flat<null[5]>?":ArrayType.Flat<null[][][][][]>;
"ArrayType.Flat<null[6]>?":ArrayType.Flat<null[][][][][][]>;
"ArrayType.Flat<null[7]>?":ArrayType.Flat<null[][][][][][][]>;
"ArrayType.Flat<null[8]>?":ArrayType.Flat<null[][][][][][][][]>;
"ArrayType.Flat<null[9]>?":ArrayType.Flat<null[][][][][][][][][]>;
"ArrayType.Flat<null[10]>?":ArrayType.Flat<null[][][][][][][][][][]>;
"ArrayType.Flat<null[11]>?":ArrayType.Flat<null[][][][][][][][][][][]>;
"ArrayType.Flat<null[12]>?":ArrayType.Flat<null[][][][][][][][][][][][]>;
"ArrayType.Flat<null[13]>?":ArrayType.Flat<null[][][][][][][][][][][][][]>;
"ArrayType.Flat<null[14]>?":ArrayType.Flat<null[][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[15]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[16]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[17]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[18]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[19]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[20]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[21]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[22]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[23]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[24]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[25]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[26]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[27]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[28]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[29]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[30]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[31]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[32]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[33]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[34]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[35]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[36]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[37]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[38]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[39]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[40]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[41]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[42]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[43]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[44]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[45]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[46]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[47]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[48]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[49]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<null[50]>?":ArrayType.Flat<null[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type boolean_arr_flat_test = {
"ArrayType.Flat<boolean[1]>?":ArrayType.Flat<boolean[]>;
"ArrayType.Flat<boolean[2]>?":ArrayType.Flat<boolean[][]>;
"ArrayType.Flat<boolean[3]>?":ArrayType.Flat<boolean[][][]>;
"ArrayType.Flat<boolean[4]>?":ArrayType.Flat<boolean[][][][]>;
"ArrayType.Flat<boolean[5]>?":ArrayType.Flat<boolean[][][][][]>;
"ArrayType.Flat<boolean[6]>?":ArrayType.Flat<boolean[][][][][][]>;
"ArrayType.Flat<boolean[7]>?":ArrayType.Flat<boolean[][][][][][][]>;
"ArrayType.Flat<boolean[8]>?":ArrayType.Flat<boolean[][][][][][][][]>;
"ArrayType.Flat<boolean[9]>?":ArrayType.Flat<boolean[][][][][][][][][]>;
"ArrayType.Flat<boolean[10]>?":ArrayType.Flat<boolean[][][][][][][][][][]>;
"ArrayType.Flat<boolean[11]>?":ArrayType.Flat<boolean[][][][][][][][][][][]>;
"ArrayType.Flat<boolean[12]>?":ArrayType.Flat<boolean[][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[13]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[14]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[15]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[16]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[17]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[18]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[19]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[20]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[21]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[22]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[23]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[24]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[25]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[26]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[27]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[28]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[29]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[30]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[31]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[32]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[33]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[34]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[35]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[36]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[37]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[38]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[39]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[40]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[41]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[42]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[43]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[44]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[45]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[46]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[47]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[48]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[49]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<boolean[50]>?":ArrayType.Flat<boolean[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type string_arr_flat_test = {
"ArrayType.Flat<string[1]>?":ArrayType.Flat<string[]>;
"ArrayType.Flat<string[2]>?":ArrayType.Flat<string[][]>;
"ArrayType.Flat<string[3]>?":ArrayType.Flat<string[][][]>;
"ArrayType.Flat<string[4]>?":ArrayType.Flat<string[][][][]>;
"ArrayType.Flat<string[5]>?":ArrayType.Flat<string[][][][][]>;
"ArrayType.Flat<string[6]>?":ArrayType.Flat<string[][][][][][]>;
"ArrayType.Flat<string[7]>?":ArrayType.Flat<string[][][][][][][]>;
"ArrayType.Flat<string[8]>?":ArrayType.Flat<string[][][][][][][][]>;
"ArrayType.Flat<string[9]>?":ArrayType.Flat<string[][][][][][][][][]>;
"ArrayType.Flat<string[10]>?":ArrayType.Flat<string[][][][][][][][][][]>;
"ArrayType.Flat<string[11]>?":ArrayType.Flat<string[][][][][][][][][][][]>;
"ArrayType.Flat<string[12]>?":ArrayType.Flat<string[][][][][][][][][][][][]>;
"ArrayType.Flat<string[13]>?":ArrayType.Flat<string[][][][][][][][][][][][][]>;
"ArrayType.Flat<string[14]>?":ArrayType.Flat<string[][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[15]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[16]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[17]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[18]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[19]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[20]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[21]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[22]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[23]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[24]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[25]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[26]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[27]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[28]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[29]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[30]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[31]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[32]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[33]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[34]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[35]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[36]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[37]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[38]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[39]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[40]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[41]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[42]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[43]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[44]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[45]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[46]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[47]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[48]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[49]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<string[50]>?":ArrayType.Flat<string[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type number_arr_flat_test = {
"ArrayType.Flat<number[1]>?":ArrayType.Flat<number[]>;
"ArrayType.Flat<number[2]>?":ArrayType.Flat<number[][]>;
"ArrayType.Flat<number[3]>?":ArrayType.Flat<number[][][]>;
"ArrayType.Flat<number[4]>?":ArrayType.Flat<number[][][][]>;
"ArrayType.Flat<number[5]>?":ArrayType.Flat<number[][][][][]>;
"ArrayType.Flat<number[6]>?":ArrayType.Flat<number[][][][][][]>;
"ArrayType.Flat<number[7]>?":ArrayType.Flat<number[][][][][][][]>;
"ArrayType.Flat<number[8]>?":ArrayType.Flat<number[][][][][][][][]>;
"ArrayType.Flat<number[9]>?":ArrayType.Flat<number[][][][][][][][][]>;
"ArrayType.Flat<number[10]>?":ArrayType.Flat<number[][][][][][][][][][]>;
"ArrayType.Flat<number[11]>?":ArrayType.Flat<number[][][][][][][][][][][]>;
"ArrayType.Flat<number[12]>?":ArrayType.Flat<number[][][][][][][][][][][][]>;
"ArrayType.Flat<number[13]>?":ArrayType.Flat<number[][][][][][][][][][][][][]>;
"ArrayType.Flat<number[14]>?":ArrayType.Flat<number[][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[15]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[16]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[17]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[18]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[19]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[20]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[21]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[22]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[23]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[24]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[25]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[26]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[27]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[28]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[29]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[30]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[31]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[32]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[33]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[34]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[35]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[36]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[37]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[38]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[39]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[40]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[41]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[42]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[43]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[44]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[45]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[46]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[47]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[48]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[49]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<number[50]>?":ArrayType.Flat<number[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type object_arr_flat_test = {
"ArrayType.Flat<object[1]>?":ArrayType.Flat<object[]>;
"ArrayType.Flat<object[2]>?":ArrayType.Flat<object[][]>;
"ArrayType.Flat<object[3]>?":ArrayType.Flat<object[][][]>;
"ArrayType.Flat<object[4]>?":ArrayType.Flat<object[][][][]>;
"ArrayType.Flat<object[5]>?":ArrayType.Flat<object[][][][][]>;
"ArrayType.Flat<object[6]>?":ArrayType.Flat<object[][][][][][]>;
"ArrayType.Flat<object[7]>?":ArrayType.Flat<object[][][][][][][]>;
"ArrayType.Flat<object[8]>?":ArrayType.Flat<object[][][][][][][][]>;
"ArrayType.Flat<object[9]>?":ArrayType.Flat<object[][][][][][][][][]>;
"ArrayType.Flat<object[10]>?":ArrayType.Flat<object[][][][][][][][][][]>;
"ArrayType.Flat<object[11]>?":ArrayType.Flat<object[][][][][][][][][][][]>;
"ArrayType.Flat<object[12]>?":ArrayType.Flat<object[][][][][][][][][][][][]>;
"ArrayType.Flat<object[13]>?":ArrayType.Flat<object[][][][][][][][][][][][][]>;
"ArrayType.Flat<object[14]>?":ArrayType.Flat<object[][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[15]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[16]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[17]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[18]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[19]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[20]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[21]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[22]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[23]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[24]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[25]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[26]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[27]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[28]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[29]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[30]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[31]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[32]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[33]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[34]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[35]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[36]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[37]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[38]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[39]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[40]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[41]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[42]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[43]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[44]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[45]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[46]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[47]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[48]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[49]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<object[50]>?":ArrayType.Flat<object[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type object_literal_arr_flat_test = {
"ArrayType.Flat<{}[1]>?":ArrayType.Flat<{}[]>;
"ArrayType.Flat<{}[2]>?":ArrayType.Flat<{}[][]>;
"ArrayType.Flat<{}[3]>?":ArrayType.Flat<{}[][][]>;
"ArrayType.Flat<{}[4]>?":ArrayType.Flat<{}[][][][]>;
"ArrayType.Flat<{}[5]>?":ArrayType.Flat<{}[][][][][]>;
"ArrayType.Flat<{}[6]>?":ArrayType.Flat<{}[][][][][][]>;
"ArrayType.Flat<{}[7]>?":ArrayType.Flat<{}[][][][][][][]>;
"ArrayType.Flat<{}[8]>?":ArrayType.Flat<{}[][][][][][][][]>;
"ArrayType.Flat<{}[9]>?":ArrayType.Flat<{}[][][][][][][][][]>;
"ArrayType.Flat<{}[10]>?":ArrayType.Flat<{}[][][][][][][][][][]>;
"ArrayType.Flat<{}[11]>?":ArrayType.Flat<{}[][][][][][][][][][][]>;
"ArrayType.Flat<{}[12]>?":ArrayType.Flat<{}[][][][][][][][][][][][]>;
"ArrayType.Flat<{}[13]>?":ArrayType.Flat<{}[][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[14]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[15]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[16]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[17]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[18]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[19]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[20]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[21]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[22]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[23]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[24]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[25]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[26]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[27]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[28]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[29]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[30]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[31]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[32]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[33]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[34]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[35]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[36]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[37]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[38]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[39]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[40]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[41]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[42]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[43]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[44]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[45]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[46]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[47]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[48]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[49]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<{}[50]>?":ArrayType.Flat<{}[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};


type arrow_func_arr_flat_test = {
"ArrayType.Flat<((...args: any) => any)[1]>?":ArrayType.Flat<((...args: any) => any)[]>;
"ArrayType.Flat<((...args: any) => any)[2]>?":ArrayType.Flat<((...args: any) => any)[][]>;
"ArrayType.Flat<((...args: any) => any)[3]>?":ArrayType.Flat<((...args: any) => any)[][][]>;
"ArrayType.Flat<((...args: any) => any)[4]>?":ArrayType.Flat<((...args: any) => any)[][][][]>;
"ArrayType.Flat<((...args: any) => any)[5]>?":ArrayType.Flat<((...args: any) => any)[][][][][]>;
"ArrayType.Flat<((...args: any) => any)[6]>?":ArrayType.Flat<((...args: any) => any)[][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[7]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[8]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[9]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[10]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[11]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[12]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[13]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[14]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[15]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[16]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[17]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[18]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[19]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[20]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[21]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[22]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[23]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[24]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[25]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[26]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[27]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[28]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[29]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[30]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[31]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[32]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[33]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[34]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[35]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[36]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[37]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[38]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[39]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[40]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[41]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[42]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[43]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[44]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[45]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[46]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[47]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[48]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[49]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>;
"ArrayType.Flat<((...args: any) => any)[50]>?":ArrayType.Flat<((...args: any) => any)[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]>
};
